### ISSUE TITLE
Ask about "pvt":   "cvt":    "crt":

### ISSUE THREAD

**Issue by 2uanDM** [pandas9/ebay-captcha-example#1]
Can you explain me what are they ? If we fix them, is it still oke to put them in captchaTokenInput in captcha submit's payload

**Comment by pandas9** [comment]
It's a timestamp but their server doesn't validate it and yes you want to submit it with a captcha payload

You could for example replace it with `int(datetime.timestamp(datetime.now()) * 1000)`
